/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripDetailTripIdIndexRouteImport } from './routes/tripDetail/$tripId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripDetailTripIdIndexRoute = TripDetailTripIdIndexRouteImport.update({
  id: '/tripDetail/$tripId/',
  path: '/tripDetail/$tripId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tripDetail/$tripId': typeof TripDetailTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tripDetail/$tripId': typeof TripDetailTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tripDetail/$tripId/': typeof TripDetailTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tripDetail/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tripDetail/$tripId'
  id: '__root__' | '/' | '/tripDetail/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripDetailTripIdIndexRoute: typeof TripDetailTripIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tripDetail/$tripId/': {
      id: '/tripDetail/$tripId/'
      path: '/tripDetail/$tripId'
      fullPath: '/tripDetail/$tripId'
      preLoaderRoute: typeof TripDetailTripIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripDetailTripIdIndexRoute: TripDetailTripIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
